CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS destinations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  province VARCHAR(80) NOT NULL,
  cover_url VARCHAR(500) NOT NULL,
  slogan VARCHAR(255) NOT NULL,
  reason TEXT NOT NULL,
  best_months JSON NOT NULL,
  suggested_days TINYINT UNSIGNED NOT NULL,
  budget_min INT UNSIGNED NOT NULL,
  budget_max INT UNSIGNED NOT NULL,
  styles JSON NOT NULL,
  seasonal_score DECIMAL(5,2) NOT NULL,
  features JSON NOT NULL,
  route JSON NOT NULL,
  tips JSON NOT NULL,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attractions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  destination_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  tag VARCHAR(40) NOT NULL,
  FOREIGN KEY (destination_id) REFERENCES destinations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS data_sources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  provider VARCHAR(100) NOT NULL,
  source_type ENUM('manual','licensed_api','open_api','reference') NOT NULL,
  license_note VARCHAR(500) NOT NULL,
  trust_level ENUM('reference','verified','live') NOT NULL DEFAULT 'reference',
  collected_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transport_searches (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  origin VARCHAR(100) NOT NULL,
  destination VARCHAR(100) NOT NULL,
  departure_date DATE NOT NULL,
  return_date DATE NULL,
  travelers TINYINT UNSIGNED NOT NULL,
  budget INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transport_options (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  search_id BIGINT UNSIGNED NOT NULL,
  provider_ref VARCHAR(120) NOT NULL,
  mode ENUM('flight','train','bus','drive','mixed') NOT NULL,
  title VARCHAR(150) NOT NULL,
  detail JSON NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  reference_only BOOLEAN NOT NULL DEFAULT TRUE,
  price_updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (search_id) REFERENCES transport_searches(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  destination_id BIGINT UNSIGNED NOT NULL,
  destination_snapshot JSON NOT NULL,
  transport_snapshot JSON NULL,
  search_snapshot JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_destination (user_id, destination_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (destination_id) REFERENCES destinations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('editor','admin') NOT NULL DEFAULT 'editor',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
